### PR TITLE
Fix AoT on Win32 & Win64

### LINKED ISSUE #531: AoT loading failure(s)
Hey there.

I've had great luck with the interpreter, but I'm wanting to give the AoT compilation a try. I'm on Windows, and trying to target x86 specifically (not x64). So, my .wasm runs great in the interpreter, and I compile it via `wamrc --target=i386`. When loading, however, `wasm_runtime_load` throws this error:

`AOT module load failed: resolve symbol ceilf failed`

In other tests, it also failed on a `__udivdi3` function, but this is the first time I've seen it reference a C library function. I'm using WASI, but without the linked library (just using the static routines, basically), so these should be linked into the .wasm (they run fine in the interpreter). Where should I be looking to resolve this?

### PR DESCRIPTION
**Pull request by Paril**
This fixes #531 and implements the missing functions that were patched out in PR #322. Allows AoT to work on Windows.

### CODE REVIEW

File: core/iwasm/aot/aot_reloc.h [hunk 1]
```diff
@@ -37,19 +37,6 @@ typedef struct {
...
-    REG_SYM(aot_invoke_native),           \
-    REG_SYM(aot_call_indirect),           \
-    REG_SYM(wasm_runtime_enlarge_memory), \
-    REG_SYM(wasm_runtime_set_exception),  \
-    {"memset", (void*)aot_memset},        \
-    {"memmove", (void*)aot_memmove},      \
-    REG_BULK_MEMORY_SYM()                 \
-    REG_ATOMIC_WAIT_SYM()                 \
-    REG_AOT_TRACE_SYM()
-#else /* else of (defined(_WIN32) || defined(_WIN32_)) && defined(NDEBUG) */
```
Comment (xujuntwt95329) [inline core/iwasm/aot/aot_reloc.h:52]: some symbols are not exists in Win64 Release build, maybe we need to reserve these code but change `WIN32` to `WIN64`

``` C
#if (defined(_WIN64) || defined(_WIN64_)) && defined(NDEBUG)
#define REG_COMMON_SYMBOLS                \
REG_SYM(aot_set_exception_with_id),       \
    REG_SYM(aot_invoke_native),           \
    REG_SYM(aot_call_indirect),           \
    REG_SYM(wasm_runtime_enlarge_memory), \
    REG_SYM(wasm_runtime_set_exception),  \
    {"memset", (void*)aot_memset},        \
    {"memmove", (void*)aot_memmove},      \
    REG_SYM(fmin),                        \
    REG_SYM(fminf),                       \
    REG_SYM(fmax),                        \
    REG_SYM(fmaxf),                       \
    REG_SYM(trunc),                       \
    REG_SYM(truncf),                      \
    REG_SYM(rint),                        \
    REG_SYM(rintf),                       \
    REG_BULK_MEMORY_SYM()                 \
    REG_ATOMIC_WAIT_SYM()                 \
    REG_AOT_TRACE_SYM()
#else /* else of (defined(_WIN64) || defined(_WIN64_)) && defined(NDEBUG) */
...
```

Comment (Paril) [reply core/iwasm/aot/aot_reloc.h:52]: Oh interesting. I'll try the win64 build here. I'd rather get Win64 building properly than have them removed.

Comment (Paril) [reply core/iwasm/aot/aot_reloc.h:52]: I pushed an update with x64 AoT relocs in place. I totally forgot about that, my bad!

**Review by xujuntwt95329 — COMMENTED** [review]
Looks good to me.

File: core/iwasm/aot/aot_runtime.c [hunk 2]
```diff
@@ -2264,7 +2264,7 @@ aot_get_module_inst_mem_consumption(const AOTModuleInstance *module_inst,
         mem_conspn->memories_size +=
             mem_inst->num_bytes_per_page * mem_inst->cur_page_count;
         mem_conspn->app_heap_size =
-            mem_inst->heap_data_end.ptr - mem_inst->heap_data.ptr;
+            (uint8_t *) mem_inst->heap_data_end.ptr - (uint8_t *) mem_inst->heap_data.ptr;
```
Comment (wenyongh) [inline core/iwasm/aot/aot_runtime.c:2267]: Hi, @Paril, we defined uint8, int64, uint64 types in the platform header file, and usually use them inside runtime instead of uint8_t, int64_t, uint64_t and so on. Could you please modify the related changes so that the coding style is unified?

File: core/iwasm/aot/arch/aot_reloc_x86_32.c [hunk 3]
```diff
@@ -8,20 +8,43 @@
...
+#if !defined(_WIN32) && !defined(_WIN32_)
 void __divdi3();
 void __udivdi3();
 void __moddi3();
 void __umoddi3();
+#else
+#pragma function (floor)
+#pragma function (ceil)
+
+int64_t __divdi3(int64_t a, int64_t b)
```
Comment (wenyongh) [inline core/iwasm/aot/arch/aot_reloc_x86_32.c:20]: Same as above

File: core/iwasm/aot/arch/aot_reloc_x86_64.c [hunk 4]
```diff
@@ -14,10 +14,37 @@
...
 void __udivdi3();
 void __moddi3();
 void __umoddi3();
+#else
+#pragma function (floor)
+#pragma function (ceil)
+#pragma function (floorf)
+#pragma function (ceilf)
+
+int64_t __divdi3(int64_t a, int64_t b)
```
Comment (wenyongh) [inline core/iwasm/aot/arch/aot_reloc_x86_64.c:28]: Same as above

File: core/iwasm/aot/aot_runtime.c (hunk 2 above)
Comment (Paril) [reply core/iwasm/aot/aot_runtime.c:2267]: Oops, will do.
