### PR TITLE
wasm_loader allocates more spaces for elements

### LINKED ISSUE #4096: [gc]  array as a field in struct object is not supported in constant init expr
### Steps to reproduce

1. Unpack zip [globals.zip](https://github.com/user-attachments/files/18892034/globals.zip)

2. Build `iwasm` with the following command:
```
cmake .. -DWAMR_BUILD_GC=1 -DWAMR_BUILD_EXCE_HANDLING=1 -DWAMR_BUILD_TAIL_CALL=1 && make
```

3.  Run `./iwasm globals.wasm`

### Expected behavior

It should print something like:
```
line 1
line 2
line 3
```

### Actual behavior

I get the following output:
```
WASM module instantiate failed: array as a field in struct object is not supported in constant init expr
unhandled SIGSEGV, si_addr: 0x21
Abandon (core dumped)
```

### PR DESCRIPTION
**Pull request by lum1n0us**
fix #4096

### CODE REVIEW

File: core/iwasm/interpreter/wasm_loader.c [hunk 1]
```diff
@@ -1073,23 +1074,24 @@ load_init_expr(WASMModule *module, const uint8 **p_buf, const uint8 *buf_end,
...
                                         &const_expr_ctx, NULL, VALUE_TYPE_I32,
                                         NULL, NULL, &len_val, error_buf,
                                         error_buf_size)) {
-                                    destroy_init_expr_data_recursive(
-                                        module, array_init_values);
                                     goto fail;
                                 }
+
+                                size = sizeof(WASMArrayNewInitValues)
+                                       + sizeof(WASMValue) * len_val.i32;
```
Comment (wenyongh) [inline core/iwasm/interpreter/wasm_loader.c:1088]: had better change `len_val.i32` to `(uint64)len_val.i32` to avoid possible integer overflow on 32-bit platform? Since in 32-bit, sizeof(..) is 32 bit.

**Review by wenyongh — APPROVED** [review]
LGTM with minor issue

**Review by TianlongLiang — APPROVED** [review]
LGTM

**Comment by vouillon** [comment]
Thanks! But this is not a complete fix to #4096. The example no longer crashes, but one still gets an error message.
